INSERT INTO BUSINESS VALUES('B1','The Factory - Cafe With a Soul','Austin');
INSERT INTO BUSINESS VALUES('B2','The Marvelous Vintage Tea Party Co.','Austin');
INSERT INTO BUSINESS VALUES('B3','Vintage Heart Coffee','Austin');
INSERT INTO BUSINESS VALUES('B4','Fleet Coffee','Austin');
INSERT INTO BUSINESS VALUES('B5','Mozartâ€™s Coffee Roasters','Austin');
INSERT INTO BUSINESS VALUES('B6','Summermoon Coffee Bar','Austin');
INSERT INTO BUSINESS VALUES('B7','Monkey Nest Coffee','Austin');
INSERT INTO BUSINESS VALUES('B8','Apanas Coffee & Beer','Austin');
INSERT INTO BUSINESS VALUES('B9','Corona Coffee','Austin');
INSERT INTO BUSINESS VALUES('B10','CafÃ© CrÃ¨me','Austin');
INSERT INTO BUSINESS VALUES('B11','Brianâ€™s Brew','Austin');
INSERT INTO BUSINESS VALUES('B12','Legend Coffee','Austin');
INSERT INTO BUSINESS VALUES('B13','Venezia Italian Gelato','Austin');
INSERT INTO BUSINESS VALUES('B14','Epoch Coffee','Austin');
INSERT INTO BUSINESS VALUES('B15','Houndstooth Coffee','Austin');
INSERT INTO BUSINESS VALUES('B16','CaffÃ© Medici','Austin');
INSERT INTO BUSINESS VALUES('B17','Flitch Coffee','Austin');
INSERT INTO BUSINESS VALUES('B18','Caffe Medici','Austin');
INSERT INTO BUSINESS VALUES('B19','Holy Grounds','Austin');
INSERT INTO BUSINESS VALUES('B20','Figure 8 Coffee Purveyors','Austin');
INSERT INTO BUSINESS VALUES('B21','MaÃ±ana Coffee & Juice','Austin');
INSERT INTO BUSINESS VALUES('B22','Summer Moon Coffee Bar','Austin');
INSERT INTO BUSINESS VALUES('B23','Fat Cats Organic Coffee And Dessert','Austin');
INSERT INTO BUSINESS VALUES('B24','Flat Track Coffee','Austin');
INSERT INTO BUSINESS VALUES('B25','Maryâ€™s Cafe','Austin');
INSERT INTO BUSINESS VALUES('B26','Andersonâ€™s Coffee Company','Austin');
INSERT INTO BUSINESS VALUES('B27','Flightpath Coffeehouse','Austin');
INSERT INTO BUSINESS VALUES('B28','Third Coast Coffee Roasting Company','Austin');
INSERT INTO BUSINESS VALUES('B29','Bennu Coffee','Austin');
INSERT INTO BUSINESS VALUES('B30','Dolce Neve','Austin');
INSERT INTO BUSINESS VALUES('B31','Thunderbird Coffee','Austin');
INSERT INTO BUSINESS VALUES('B32','Halcyon','Austin');
INSERT INTO BUSINESS VALUES('B33','Cherrywood Coffeehouse','Austin');
INSERT INTO BUSINESS VALUES('B34','Joâ€™s Coffee','Austin');
INSERT INTO BUSINESS VALUES('B35','Arturoâ€™s Underground Cafe','Austin');
INSERT INTO BUSINESS VALUES('B36','Patika','Austin');
INSERT INTO BUSINESS VALUES('B37','Cenote','Austin');
INSERT INTO BUSINESS VALUES('B38','The Hideout Coffeehouse','Austin');
INSERT INTO BUSINESS VALUES('B39','Lucky Lab Coffee','Austin');
INSERT INTO BUSINESS VALUES('B40','Cream Whiskers','Austin');
INSERT INTO BUSINESS VALUES('B41','Lola Savannah Coffee Lounge','Austin');
INSERT INTO BUSINESS VALUES('B42','Seventh Flag Coffee Co','Austin');
INSERT INTO BUSINESS VALUES('B43','Irie Bean Coffee Bar','Austin');
INSERT INTO BUSINESS VALUES('B44','Sa-Ten','Austin');
INSERT INTO BUSINESS VALUES('B45','Tea Haus','Austin');
INSERT INTO BUSINESS VALUES('B46','Friends & Neighbors','Austin');
INSERT INTO BUSINESS VALUES('B47','Sorrentoâ€™s Coffee','Austin');
INSERT INTO BUSINESS VALUES('B48','Elixer Coffee','Austin');
INSERT INTO BUSINESS VALUES('B49','Cafe Ruckus','Austin');
INSERT INTO BUSINESS VALUES('B50','The Buzz Mill','Austin');
INSERT INTO BUSINESS VALUES('B51','Once Over Coffee Bar','Austin');
INSERT INTO BUSINESS VALUES('B52','TOMS','Austin');
INSERT INTO BUSINESS VALUES('B53','Genuine Joe','Austin');
INSERT INTO BUSINESS VALUES('B54','CuvÃ©e Coffee Bar','Austin');
INSERT INTO BUSINESS VALUES('B55','Radio Coffee & Beer','Austin');
INSERT INTO BUSINESS VALUES('B56','Dominican Joe','Austin');
INSERT INTO BUSINESS VALUES('B57','Trianon Coffee','Austin');
INSERT INTO BUSINESS VALUES('B58','Picnik Austin','Austin');
INSERT INTO BUSINESS VALUES('B59','Kowabunga Coffee','Austin');
INSERT INTO BUSINESS VALUES('B60','Kick Butt Coffee Music & Booze','Austin');
INSERT INTO BUSINESS VALUES('B61','La Tazza Fresca','Austin');
INSERT INTO BUSINESS VALUES('B62','Stinsonâ€™s','Austin');
INSERT INTO BUSINESS VALUES('B63','Sister Coffee','Austin');
INSERT INTO BUSINESS VALUES('B64','Pacha','Austin');
INSERT INTO BUSINESS VALUES('B65','Strange Brew, Austin Coffee','Austin');
INSERT INTO BUSINESS VALUES('B66','Quackâ€™s 43rd Street Bakery','Austin');
INSERT INTO BUSINESS VALUES('B67','Juan Pelota','Austin');
INSERT INTO BUSINESS VALUES('B68','Altaâ€™s Cafe','Austin');
INSERT INTO BUSINESS VALUES('B69','Teo','Austin');
INSERT INTO BUSINESS VALUES('B70','La Patisserie','Austin');
INSERT INTO BUSINESS VALUES('B71','My Sweet Austin','Austin');
INSERT INTO BUSINESS VALUES('B72','Lola Savannah Coffee Downtown','Austin');
INSERT INTO BUSINESS VALUES('B73','Tuscany At 360','Austin');
INSERT INTO BUSINESS VALUES('B74','CafÃ© Java','Austin');
INSERT INTO BUSINESS VALUES('B75','Russellâ€™s Bakery','Austin');
INSERT INTO BUSINESS VALUES('B76','Emerald Tavern Games & Cafe','Austin');
INSERT INTO BUSINESS VALUES('B77','Live Oak Market','Austin');
INSERT INTO BUSINESS VALUES('B78','Hot Mamaâ€™s Cafe','Austin');
INSERT INTO BUSINESS VALUES('B79','The Steeping Room','Austin');